"""
database/models.py
───────────────────
All database table definitions.

Tables:
  metal_prices     — every scraped price per source per run
  forex_rates      — USD/INR history
  margin_analyses  — every BUY/STOP calculation ever run
  news_articles    — scraped headlines + metadata
  sentiment_scores — daily sentiment per metal
  lme_inventory    — LME warehouse stock history
  forecasts        — agent forecast outputs
  price_predictions — ML-style predictions generated by prediction agent
"""

from datetime import datetime
from sqlalchemy import (
    Column, Integer, Float, String, Boolean,
    DateTime, Text, JSON, Index, ForeignKey
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class MetalPrice(Base):
    """
    Every metal price scraped — one row per metal per source per run.
    Lets us track source reliability and price drift over time.
    """
    __tablename__ = "metal_prices"

    id            = Column(Integer, primary_key=True, autoincrement=True)
    scraped_at    = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    run_id        = Column(String(36), nullable=False, index=True)  # UUID per analysis run

    metal         = Column(String(32), nullable=False, index=True)  # nickel, cobalt, etc.
    chemistry     = Column(String(32), nullable=False)              # NMC, LCO, etc.

    # The consensus price (median of all sources)
    consensus_price_usd = Column(Float, nullable=False)
    unit          = Column(String(32), default="USD/tonne")

    # Source breakdown
    source_count  = Column(Integer, default=1)
    spread_pct    = Column(Float, default=0.0)      # % spread between sources
    confidence    = Column(String(32), default="LOW")  # HIGH / MEDIUM / LOW

    # Individual source prices stored as JSON
    # {"investing.com": 16450, "tradingeconomics.com": 16460, "mcx": 16445}
    source_prices = Column(JSON, default=dict)

    # Derived
    price_inr_per_kg = Column(Float, nullable=True)  # converted at run time
    usd_inr_rate     = Column(Float, nullable=True)

    # 30-day sparkline stored for charting
    chart_data    = Column(JSON, default=list)

    __table_args__ = (
        Index("ix_metal_scraped", "metal", "scraped_at"),
    )


class ForexRate(Base):
    """Historical USD/INR rates."""
    __tablename__ = "forex_rates"

    id         = Column(Integer, primary_key=True, autoincrement=True)
    fetched_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    rate       = Column(Float, nullable=False)
    source     = Column(String(128), nullable=False)
    stale      = Column(Boolean, default=False)


class MarginAnalysis(Base):
    """
    Every BUY/STOP decision ever calculated.
    This is the core prediction training data over time.
    """
    __tablename__ = "margin_analyses"

    id            = Column(Integer, primary_key=True, autoincrement=True)
    run_id        = Column(String(36), nullable=False, index=True)
    calculated_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    chemistry     = Column(String(32), nullable=False, index=True)
    aggregator_ask_inr = Column(Float, nullable=False)

    # Inputs
    usd_inr_rate         = Column(Float, nullable=False)
    metal_prices_json    = Column(JSON, default=dict)  # {nickel: 16450, cobalt: 25800}

    # Calculated outputs
    gross_metal_value_usd = Column(Float, nullable=False)
    selling_price_usd     = Column(Float, nullable=False)
    selling_price_inr     = Column(Float, nullable=False)
    max_buy_price_inr     = Column(Float, nullable=False)

    # Decision
    buy_decision          = Column(Boolean, nullable=False)
    margin_at_ask_pct     = Column(Float, nullable=True)
    headroom_inr          = Column(Float, nullable=True)  # max_buy - ask

    # Quality flags
    stale_data            = Column(Boolean, default=False)
    warnings              = Column(JSON, default=list)

    # Outcome tracking (filled in later if user confirms trade)
    actual_outcome        = Column(String(32), nullable=True)  # PROFITABLE, LOSS, PENDING
    outcome_notes         = Column(Text, nullable=True)


class NewsArticle(Base):
    """
    Every scraped news article. Deduplicated by headline hash.
    """
    __tablename__ = "news_articles"

    id            = Column(Integer, primary_key=True, autoincrement=True)
    scraped_at    = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    run_id        = Column(String(36), nullable=False)

    metal         = Column(String(32), nullable=False, index=True)
    chemistry     = Column(String(32), nullable=True)
    source        = Column(String(128), nullable=False)
    headline      = Column(Text, nullable=False)
    url           = Column(Text, nullable=True)
    sentiment     = Column(String(16), nullable=False)  # bullish / bearish / neutral

    # Price mentions extracted from article
    price_mentions = Column(JSON, default=list)  # [{value: 16450, unit: "USD/tonne"}]

    # Dedup key — md5 of headline
    headline_hash = Column(String(64), nullable=True, index=True)

    __table_args__ = (
        Index("ix_news_metal_scraped", "metal", "scraped_at"),
    )


class SentimentScore(Base):
    """
    Aggregated daily sentiment per metal.
    One row per metal per day — averaged over all runs that day.
    """
    __tablename__ = "sentiment_scores"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    date        = Column(String(10), nullable=False, index=True)  # YYYY-MM-DD
    metal       = Column(String(32), nullable=False, index=True)
    chemistry   = Column(String(32), nullable=True)

    bullish_count  = Column(Integer, default=0)
    bearish_count  = Column(Integer, default=0)
    neutral_count  = Column(Integer, default=0)
    total_articles = Column(Integer, default=0)

    # Computed signal
    bullish_ratio  = Column(Float, default=0.0)
    signal         = Column(String(16), default="NEUTRAL")  # BULLISH/BEARISH/MIXED

    # Average price mentioned in articles that day
    avg_price_mentioned = Column(Float, nullable=True)

    __table_args__ = (
        Index("ix_sentiment_date_metal", "date", "metal"),
    )


class LMEInventory(Base):
    """LME warehouse stock history — key supply/demand signal."""
    __tablename__ = "lme_inventory"

    id           = Column(Integer, primary_key=True, autoincrement=True)
    recorded_at  = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    metal        = Column(String(32), nullable=False, index=True)
    stock_tonnes = Column(Float, nullable=False)
    signal       = Column(String(64), nullable=True)   # "high inventory (bearish)"
    source       = Column(String(128), default="lme.com")


class Forecast(Base):
    """
    Every SELL TODAY / HOLD INVENTORY forecast generated by the crew.
    """
    __tablename__ = "forecasts"

    id           = Column(Integer, primary_key=True, autoincrement=True)
    run_id       = Column(String(36), nullable=False, index=True)
    generated_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    chemistry    = Column(String(32), nullable=False, index=True)
    signal       = Column(String(32), nullable=False)   # SELL TODAY / HOLD INVENTORY
    full_report  = Column(Text, nullable=True)

    # Context at time of forecast
    buy_decision       = Column(Boolean, nullable=True)
    selling_price_inr  = Column(Float, nullable=True)
    max_buy_price_inr  = Column(Float, nullable=True)
    aggregator_ask_inr = Column(Float, nullable=True)

    # Accuracy tracking (fill in 7 days later)
    was_correct    = Column(Boolean, nullable=True)
    accuracy_notes = Column(Text, nullable=True)


class PricePrediction(Base):
    """
    Forward price predictions generated by the Prediction Agent.
    Uses historical data patterns to predict 7/14/30 day prices.
    """
    __tablename__ = "price_predictions"

    id             = Column(Integer, primary_key=True, autoincrement=True)
    generated_at   = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    run_id         = Column(String(36), nullable=False)

    metal          = Column(String(32), nullable=False, index=True)
    chemistry      = Column(String(32), nullable=False)

    # Current price at time of prediction
    current_price_usd = Column(Float, nullable=False)

    # Predictions
    pred_7d_usd    = Column(Float, nullable=True)   # 7-day forecast
    pred_14d_usd   = Column(Float, nullable=True)   # 14-day forecast
    pred_30d_usd   = Column(Float, nullable=True)   # 30-day forecast

    # Confidence + direction
    direction      = Column(String(16), nullable=True)   # UP / DOWN / SIDEWAYS
    confidence_pct = Column(Float, nullable=True)        # 0-100

    # What signals drove this prediction
    signal_inputs  = Column(JSON, default=dict)
    # {
    #   "price_trend_7d": "+2.3%",
    #   "sentiment": "BULLISH",
    #   "lme_stock_trend": "declining",
    #   "data_points_used": 45,
    #   "reasoning": "..."
    # }

    # Accuracy (filled in after prediction window passes)
    actual_price_7d  = Column(Float, nullable=True)
    actual_price_14d = Column(Float, nullable=True)
    actual_price_30d = Column(Float, nullable=True)
    error_7d_pct     = Column(Float, nullable=True)
    error_14d_pct    = Column(Float, nullable=True)
    error_30d_pct    = Column(Float, nullable=True)

    __table_args__ = (
        Index("ix_pred_metal_date", "metal", "generated_at"),
    )
